add get_system_status
dvcrn/binance.ex pull request #43
Opened 2021-05-18 08:18 UTC by asmodehn

2021-05-18 11:52 UTC, Cinderella-Man requested changes
Hello :wave: 

Thank you very much for your PR. I checked the endpoint and it looks like `wapi` endpoints are getting delisted:

https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

You could just update the URL in the PR to `/sapi/v1/system/status `(https://binance-docs.github.io/apidocs/spot/en/#wallet-endpoints) and it should be fine.

I added 2 comments inline.

2021-05-18 11:52 UTC, Cinderella-Man commented on lib/binance.ex
> +    case HTTPClient.get_binance("/wapi/v3/systemStatus.html") do
As per my comment `wapi` endpoints are getting delisted but we could use `/sapi/v1/system/status`

2021-05-18 11:52 UTC, Cinderella-Man commented on test/binance_test.exs
> +      assert %Binance.SystemStatus{} = response
Should data inside the struct be checked here?

2021-05-18 16:03 UTC, asmodehn commented
Good catch, I hadn't noticed, thanks !

2021-05-20 12:00 UTC, Cinderella-Man commented
> Good catch, I hadn't noticed, thanks ! (deprecation date was indeed right there in the cassette data)

Ha! I missed that `Deprecation` field in the response - good catch as well! This looks good and I believe it can be merged now.

Thank you very much once again for your contribution :+1:

2021-05-20 12:02 UTC, merged